# Generated by Django 3.1.7 on 2021-04-09 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('message', models.TextField(blank=True, default='')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('public', models.BooleanField(default=False)),
                ('note_status', models.IntegerField(choices=[(0, 'Active'), (1, 'Hold'), (2, 'Done')], default=0, verbose_name='Статус дела')),
                ('important', models.BooleanField(default=False)),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='authors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
