# Generated by Django 3.2 on 2021-04-15 22:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_todo', '0003_alter_note_date_add'),
    ]

    operations = [
        migrations.DeleteModel(
            name='nlist',
        ),
        migrations.AlterField(
            model_name='note',
            name='date_add',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 16, 22, 41, 45, 709086)),
        ),
    ]
