# Generated by Django 3.2 on 2021-04-16 09:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_todo', '0004_auto_20210415_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date_add',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 17, 9, 3, 36, 235650)),
        ),
    ]
